// src/app/layout.tsx
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { NotificationProvider } from "@/hooks/use-notifications";
import { ToastContainer } from "@/components/ui/toast";
import { ThemeProvider } from "@/components/theme/theme-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} data-theme="dark">
      <body className="bg-[var(--surface-0)] text-[var(--text-primary)]">
        <NotificationProvider>
          <TRPCReactProvider>
            <ThemeProvider>
              {children}
              <ToastContainer />
            </ThemeProvider>
          </TRPCReactProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}